
CREATE TABLE CUSTOMER
  (
    ID         NUMBER NOT NULL ,
    FIRST_NAME VARCHAR2(1000 BYTE) ,
    LAST_NAME  VARCHAR2(1000 BYTE) ,
    EXTENSION CLOB ,
    AGE     NUMBER ,
    SEX     VARCHAR2(100 BYTE) ,
    COUNTY  VARCHAR2(1000 BYTE) ,
    COUNTRY VARCHAR2(1000 BYTE) ,
    EMAIL   VARCHAR2(4000 BYTE) ,
    PHONE   VARCHAR2(1000 BYTE) ,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY ( ID ),
    CONSTRAINT CHK_CUSTOMER_EXTN CHECK (EXTENSION IS JSON) ); 
/

CREATE SEQUENCE CUSTOMER_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/

Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (1,'Andy','Moore',32,'M','CA','US','andy.moore@boa.com','+19872345672');
Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (2,'Bincy','Paul',28,'F','TX','US','bincy.paul@boa.com','+14523789534');
Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (3,'Amira','Joy',32,'F','CA','US','amira.joy@boa.com','+16754230978');
/