CREATE TABLE CUSTOMER
  (
    ID         NUMBER NOT NULL ,
    FIRST_NAME VARCHAR2(1000 BYTE) ,
    LAST_NAME  VARCHAR2(1000 BYTE) ,
    EXTENSION CLOB ,
    AGE     NUMBER ,
    SEX     VARCHAR2(100 BYTE) ,
    COUNTY  VARCHAR2(1000 BYTE) ,
    COUNTRY VARCHAR2(1000 BYTE) ,
    EMAIL   VARCHAR2(4000 BYTE) ,
    PHONE   VARCHAR2(1000 BYTE) ,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY ( ID ),
    CONSTRAINT CHK_CUSTOMER_EXTN CHECK (EXTENSION IS JSON) ); 
/

CREATE SEQUENCE CUSTOMER_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/


--CITI_CUSTOMERS

Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (1,'Kaila','Bernard',38,'F','CA','US','kaila.nernard@citi.com','+18976235412');
Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (2,'Edward','Joesph',28,'M','TX','US','edward.joesph@citi.com','+19788734765');
Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (3,'Earl','John',32,'M','TX','US','earl.john@citi.com','+16345687902');
