CREATE TABLE CUSTOMER
  (
    ID         NUMBER NOT NULL ,
    FIRST_NAME VARCHAR2(1000 BYTE) ,
    LAST_NAME  VARCHAR2(1000 BYTE) ,
    EXTENSION CLOB ,
    AGE     NUMBER ,
    SEX     VARCHAR2(100 BYTE) ,
    COUNTY  VARCHAR2(1000 BYTE) ,
    COUNTRY VARCHAR2(1000 BYTE) ,
    EMAIL   VARCHAR2(4000 BYTE) ,
    PHONE   VARCHAR2(1000 BYTE) ,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY ( ID ),
    CONSTRAINT CHK_CUSTOMER_EXTN CHECK (EXTENSION IS JSON) ); 
/

CREATE SEQUENCE CUSTOMER_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/

Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (1,'Ben','Hussan',38,'M','LONDON','UK','ben.hussan@rbs.com','+448793465234');
Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (2,'Victoria','Bernard',20,'F','LIVERPOOL','UK','victoria.b@rbs.com','+445687239845');
Insert into CUSTOMER (ID,FIRST_NAME,LAST_NAME,AGE,SEX,COUNTY,COUNTRY,EMAIL,PHONE) values (3,'Johnson','Ferry',17,'M','EDINBURGH','UK','johnson.f@rbs.com','+447890235476');
/